---
- file:
    path: /opt/projects
    state: directory


- apt:
    name:
      - spamassassin
    state: present
- name: Enable and start spamassassin-maintenance.timer
  ansible.builtin.systemd:
    name: spamassassin-maintenance.timer
    enabled: true
    state: started
- name: Restart spamassassin service
  ansible.builtin.systemd:
    name: spamd
    state: restarted


- git:
    repo: https://github.com/wasya-co/annesque_email.git
    dest: /opt/projects/annesque_email
    version: 0.1.0
    accept_hostkey: true

- name: Create symlink for postal binary
  ansible.builtin.file:
    src: /opt/projects/annesque_email/bin/postal
    dest: /usr/bin/postal
    state: link
    force: yes


# - ansible.builtin.include_role:
#     name: roles/nginx
#     tasks_from: proxy-vsites

# - name: Run docker compose project
#   community.docker.docker_compose:
#     project_src: /opt/projects/annesque_email
#     state: present

