##
## syntax=docker/dockerfile:1
##
## This builds a ruby+nginx image.
##
##   docker build . -f Dockerfile-ruby275    -t piousbox/ruby275:0.0.16
##

FROM debian:bullseye

RUN apt-get update && \
  apt-get install -y \
    cron curl \
    git gnupg2 \
    imagemagick iputils-ping \
    lsof \
    net-tools \
    screen silversearcher-ag \
    telnet \
    vim \
    wget \
    unzip

RUN apt install -y \
  build-essential \
  libz-dev libcurl4-openssl-dev libssl-dev \
  nodejs \
  procps \
  tree

COPY ./root/_bashrc   /root/.bashrc
COPY ./root/_screenrc /root/.screenrc

RUN git clone https://github.com/rbenv/rbenv.git      /opt/rbenv ; \
  git   clone https://github.com/rbenv/ruby-build.git /opt/rbenv/plugins/ruby-build ; \
  . /root/.bashrc ; \
  /opt/rbenv/bin/rbenv install 2.7.5 ; \
  echo "2.7.5" > /opt/projects/.ruby-version ; \
  echo ok

RUN . /root/.bashrc ; \
  cd /opt/projects ; \
  gem install passenger --no-document ; \
  passenger-install-nginx-module --auto ; \
  echo ok


RUN apt install -y \
  libyaml-dev

WORKDIR /opt/projects/packagedapp

EXPOSE 80

## even
# CMD /bin/bash -c "source /root/.bashrc && /opt/nginx/sbin/nginx -g 'daemon off;' "
# CMD /bin/bash -c "/opt/rbenv/shims/bundle exec puma -C config/puma.rb "
## odd
CMD while true; do echo -n '.' ; sleep 15; done

