
services:

  app:
    image: piousbox/ruby275-nginx:0.0.16
    command: sh -c "/opt/rbenv/shims/bundle --path vendor/bundle && \
      /opt/rbenv/shims/bundle exec rake db:seed && \
      /opt/rbenv/shims/bundle exec rake assets:precompile && \
      /opt/rbenv/shims/bundle exec puma -C config/puma.rb "
    container_name: app
    depends_on:
      - localstack
      - mongo
    environment:
      - PORT=9002
      - EMAIL=admin@local
      - PASSWORD=test1234
      - RAILS_ENV=production
    # init: true
    networks:
      - internal_db_net
    ports:
      - 127.0.0.1:9002:9002
    volumes:
      - vendor_bundle:/opt/projects/packagedapp/vendor/bundle:cached
      - type: bind
        source: ./volumes/root
        target: /root
      - type: bind
        source: ./
        target: /opt/projects/packagedapp
    restart: 'unless-stopped'

  localstack:
    image: localstack/localstack:3.7.0
    container_name: localstack
    environment:
      - SERVICES=s3:5002
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/opt/localstack/data
      ## LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      # - DEBUG=${DEBUG:-0}
    networks:
      - internal_db_net
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway. host:container
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
      # - type: bind
      #   source: ./volumes/localstack_development_data
      #   target: /var/lib/localstack
      - localstack_data:/var/lib/localstack
      - type: bind
        source: ./tmp
        target: /opt/tmp
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./db/seed_localstack:/etc/localstack/init/ready.d
    restart: 'unless-stopped'

  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ROOT_PASSWORD: postal
    networks:
      - internal_db_net
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:5.0.7-ubuntu2004
    networks:
      - internal_db_net
    ports:
      - "127.0.0.1:27037:27017"
    volumes:
      # - type: bind
      #   source: ./volumes/mongo_data
      #   target: /data/db
      - mongo_data:/data/db
    restart: 'unless-stopped'

  web:
    container_name: postal_web
    image: ghcr.io/postalserver/postal:3.3.5
    command: postal web-server
    network_mode: host
    volumes:
      - /opt/projects/annesque_email/config/postal:/config
    restart: unless-stopped

  smtp:
    container_name: postal_smtp
    image: ghcr.io/postalserver/postal:3.3.5
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/projects/annesque_email/config/postal:/config
    restart: unless-stopped

  worker:
    container_name: postal_worker
    image: ghcr.io/postalserver/postal:3.3.5
    command: postal worker
    network_mode: host
    volumes:
      - /opt/projects/annesque_email/config/postal:/config
    restart: unless-stopped

  runner:
    container_name: postal_runner
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:3.3.5
    command: postal
    network_mode: host
    volumes:
      - /opt/projects/annesque_email/config/postal:/config

networks:
  internal_db_net:
    internal: true

volumes:
  localstack_data:
  mariadb_data:
  mongo_data:
  vendor_bundle:



