
volumes:
  bundle:
  mongo:

services:

  redis:
    image: redis
    restart: 'unless-stopped'

  app:
    image: piousbox/ruby275-nginx:0.0.10
    # container_name: app
    environment:
      RAILS_ENV: packagedenv
    ports:
      - {{ app_port }}:80 ## https
      # - 9101:22 ## ssh
    restart: 'unless-stopped'
    volumes:
      - bundle:/usr/local/bundle
      - type: bind
        source: ./volumes/packagedapp
        target: /opt/projects/packagedapp

  sidekiq:
    image: piousbox/ruby275-nginx:0.0.10
    # container_name: sidekiq
    working_dir: /opt/projects/packagedapp
    command: sidekiq
    environment:
      RAILS_ENV: packagedenv
      REDIS_URL: redis://redis:6379/0
    restart: 'unless-stopped'
    volumes:
      - bundle:/usr/local/bundle
      - type: bind
        source: ./volumes/packagedapp
        target: /opt/projects/packagedapp

  mongo:
    image: mongodb/mongodb-community-server:5.0.7-ubuntu2004
    # container_name: mongo
    # ports:
    #   - 27037:27017
    restart: 'unless-stopped'
    volumes:
      - mongo:/data/db
